wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.49.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742973253.187559
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 13
      - 23
      4: 3.10.13
      5: 0.16.2
      6: 4.49.0
      8:
      - 8
      - 15
      13: linux-x86_64
